name: Waka Readme

  on:
    schedule:
      # Runs at 12am IST
      - cron: '30 18 * * *'
    workflow_dispatch:
  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: ${{ secrets.waka_0deb97a9-d672-4fef-8684-de43e1d3d77e}}
            GH_TOKEN: ${{ secrets.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 }}
            * 기본적으로 모든 Flag를 보여줍니다. 특정 Flag는 제외하고 싶다면 옵션을 이곳에 직접 작성해야 합니다.
